services:
  etl:
    build: ./etl
    container_name: news_etl
    volumes:
      - ./data:/app/data
      - ./output:/app/output

  dashboard:
    build: ./dashboard
    container_name: news_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - etl
